### ISSUE TITLE
Missing tauGeodesic.jar

### ISSUE THREAD

**Issue by mathiasbio** [matsengrp/gapml#180]
Hi!
We've been trying to install this software and has come to the step where we're trying to find the dependencies that need to be referenced inside the constant_paths.py file. We have managed to find everything except for the TAU_GEO_JAR_PATH=".../gestaltamania-master/tauSpace/tauGeodesic.jar" referenced in the old issue below.  Maybe it disappeared in some newer version of the branch.
Thank you for any help, and for the software :) 

Referenced issue: 
For anyone interested - I had to download 2 more packages, rspr and BHVtreespace, and link their respective executables.  That's what my constant_paths.py file looks like:

```
# from https://github.com/cwhidden/rspr
RSPR_PATH=".../rspr-master/rspr"

# from https://github.com/gavruskin/tauGeodesic
#could be a different program within the BHV package.... in distances only robinson Foulds distance is used
BHV_PATH=".../BHVtreespace-master/Distances.jar"

# from within gestaltamania 
TAU_GEO_JAR_PATH=".../gestaltamania-master/tauSpace/tauGeodesic.jar"

# as specified on gestaltamania README
MIX_PATH=".../phylip-3.695/exe/mix"
```

_Originally posted by @seidels in https://github.com/matsengrp/gapml/issues/173#issuecomment-580736445_

**Comment by jjfeng** [comment]
Hello! Thanks for raising this issue. Sorry about the confusion. I had removed `tauGeodesic.jar` because we decided not to use that method for measuring distance. I have removed the line with `TAU_GEO_JAR_PATH` from any files that referenced it.

**Comment by mathiasbio** [comment]
Thank you, it works! :)
